In [ ]:
#Import required python module(s)
import numpy as np 

In [ ]:
#load data from file
#data = np.genfromtxt('iris_multiclass.csv', delimiter=',',skip_header=True)
data = np.genfromtxt('/content/drive/My Drive/Machine Learning Algorithm/Logistic Regression/iris_multiclass.csv', delimiter=',',skip_header=True)
#Distribute data into train and test sets
X_train = data[:120,[0,1,2,3]]
Y_train = data[:120,5]

X_test = data[-30:,[0,1,2,3]]
Y_test = data[-30:,5]
print(Y_train)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [ ]:
#Define the required Sigmoid function
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [ ]:
#Define the Raw implementation function to set the parameters (theta)

def fit_implementation(X_train, Y_train, learning_rate=0.0005, max_iteration=1000, debug=False):
  #Adding a column of 1's so that the first element of each input is always 1
  #It would be multiplied with theta_0 later
  X_train= np.insert(X_train, 0, values=1, axis=1)
  no_attributes = X_train.shape[1]

  #Initialize model parameters theta
  theta = np.zeros((no_attributes,1))

  #Run number of iterations
  for icount in range(max_iteration):
    #delta is the quantity that will be added with theta during updating theta
    delta = np.zeros((no_attributes,1))
    totalLogLikelihood = 0
    #Check each data point
    for instance, actualOutput in zip(X_train,Y_train):
      instance=instance.reshape(no_attributes,1)
      dotResult = np.dot(theta.T, instance)
      
      predictedValue=sigmoid(dotResult).squeeze()
      #Calculate the derivative value for this data point
      derivativeValue = instance*(actualOutput-predictedValue)
      #Calculate the amount to be added with theta
      delta += learning_rate*derivativeValue

      logLikelihood = actualOutput*np.log(predictedValue)+(1-actualOutput)*np.log(1-predictedValue)
      totalLogLikelihood += logLikelihood
    theta = theta + delta
      
    #After each 100 iteration, print the status
    if icount%100==0 and debug==True:
      print(icount)
      print(totalLogLikelihood)
      print(theta)
          
  print(totalLogLikelihood)
  print(theta)

  return theta


def multciClassFitImplementation(X_train, Y_train):
  #Determine the list unique classes (unique target variable values) 
  #Changes required here
  unique_list = np.unique(Y_train)

  #For each uniqueclass, determine the best classifier/parameter/theta which best separates the class with others
  #You can temporarily modify Y_train data to achieve the target and can call the fit_implementation function
  parameters = dict()
  #Changes required here
  for val in unique_list:
    updated_Y = np.where(Y_train == val, 1, 0)
    temp_theta = fit_implementation(X_train,updated_Y)
    parameters[val] = temp_theta  
  return parameters
        
parameters = multciClassFitImplementation(X_train, Y_train)
print(parameters)

-1.3879260321845126
[[ 0.28590272]
 [ 0.46011454]
 [ 1.60972781]
 [-2.50791129]
 [-1.14796962]]
-64.76128269268942
[[ 0.63087103]
 [ 0.42606365]
 [-1.40136046]
 [ 0.32136084]
 [-0.77762565]]
-19.378481198390663
[[-0.93309689]
 [-1.69285985]
 [-1.54003974]
 [ 2.58282908]
 [ 2.00266044]]
{1.0: array([[ 0.28590272],
       [ 0.46011454],
       [ 1.60972781],
       [-2.50791129],
       [-1.14796962]]), 2.0: array([[ 0.63087103],
       [ 0.42606365],
       [-1.40136046],
       [ 0.32136084],
       [-0.77762565]]), 3.0: array([[-0.93309689],
       [-1.69285985],
       [-1.54003974],
       [ 2.58282908],
       [ 2.00266044]])}


In [ ]:
#One of the following parameters of the function is now thetas which is a dictionary containing (targetClass,theta) 
#as (key,value) pairs for all target classes
def prediction(X_test, Y_test, thetas):
  #Adding a column of 1's so that the first element of each input is always 1
  #It would be multiplied with theta_0 later
  X_test= np.insert(X_test, 0, values=1, axis=1)
  no_attributes = X_test.shape[1]
  
  correctCount = 0
  totalCount = 0
  
  maxPredictedValue = -10000
  predictedClass = 1.0
  
  #Check each data point
  for instance, actualOutput in zip(X_test,Y_test):
          instance=instance.reshape(no_attributes,1)
          #Determine the maximum predicted value and predictedClass
          #Changes required here
          maxPredictedValue = -10000
          predictedClass = 0
          for pair in thetas:
            theta = thetas[pair]
            dotResult = np.dot(theta.T, instance)
            predictedValue=sigmoid(dotResult).squeeze()
            if predictedValue > maxPredictedValue:
              maxPredictedValue = predictedValue
              predictedClass = pair
              
          print(maxPredictedValue, predictedClass, actualOutput)
          if predictedClass == actualOutput:
              correctCount += 1
          totalCount += 1
  print("Total Correct Count: ",correctCount," Total Wrong Count: ",totalCount-correctCount," Accuracy: ",(correctCount*100)/(totalCount))
  
prediction(X_test, Y_test, parameters)

0.9697683923707109 1.0 1.0
0.9890910258920178 1.0 1.0
0.9783928902171469 1.0 1.0
0.9908882941076916 1.0 1.0
0.984600599550169 1.0 1.0
0.38952320581739663 2.0 2.0
0.3000647046445209 2.0 2.0
0.40968262184108 2.0 2.0
0.5064051681035897 2.0 2.0
0.4472710056158424 2.0 2.0
0.7579463324970365 3.0 3.0
0.7809116479331422 3.0 3.0
0.7066620010675335 3.0 3.0
0.8685767540093352 3.0 3.0
0.7748892942898554 3.0 3.0
0.9902031306978576 1.0 1.0
0.9208619677655475 1.0 1.0
0.9815062786088594 1.0 1.0
0.9712258873104448 1.0 1.0
0.9713972683520286 1.0 1.0
0.3943257386613801 2.0 2.0
0.2605286759263265 2.0 2.0
0.41051977878748 2.0 2.0
0.46164855771225216 2.0 2.0
0.31590832996990326 2.0 2.0
0.9021060040231639 3.0 3.0
0.5964257475129733 3.0 3.0
0.887723108886421 3.0 3.0
0.9221654716528381 3.0 3.0
0.9146192987919184 3.0 3.0
Total Correct Count:  30  Total Wrong Count:  0  Accuracy:  100.0
